# Site settings
title: Josh R.
description: >
  My thoughts on technology, life and stuff.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://joshuarussell.ca" # the base hostname & protocol for your site

author:
  fullname: Joshua Russell
  googleplus: https://www.google.com/+JoshRussell91
  github: JoshR604
  twitter: joshrussell91
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
